### ISSUE TITLE
Limit message size

### ISSUE THREAD

**Issue by DerGolo** [demel42/IPSymconNotification#1]
Der Versand von Nachrichten ist Plattform spezifisch in der Länge beschränkt. Apple z.B. limitiert die Anzahl der Zeichen (meines Wissens nach) auf 178 (siehe [hier](https://clevertap.com/blog/what-are-push-notification-character-limits/#:~:text=What%20Are%20App%20Push%20Notification,titles%20and%20240%20for%20descriptions.)). Nachrichten über dem Limit werden einfach nicht zugestellt und verschwinden im digitalen Nirvana.

Es wäre toll, wenn sich ein Limit für die maximale Nachrichtenlänge konfigurieren ließe und die Nachrichten vor Versand automatisch entsprechend gekürzt würden. Gerade bei automatischen und wichtigen Meldungen ist so sichergestellt, dass die Nachricht auch ankommt, lieber zu kurz als gar nicht.

**Comment by demel42** [comment]
Das Modul hat ja 4 unterstützte Kommunikationswege

1. Webfront (WF)
hier berücksichtige ich die internen Limitierungen vom IPS
2. SMS
hier mache ich keine Längenprüfung unter dem Hintergrund, das manche Provider aus einer zu langen SMS mehrere SMS machen. Hier könnte ich mir vorstellen, das die Angabe der Limitierung auf 140 Zeichen i.O. ist, wobei man schon das Problem hab, das man nicht weis, wie UFT-Buchstaben von der SMS gezählt werden
3. Mail
hier gibt's keine Limits, zumindest nicht in einem relevanten Bereich
4. Script
ich nehme an, das Du dich hierauf beziehst? Da ich ja hier keine weiteren Typen, insbesondere nicht Apple Push direkt integriert habe.
An der Stelle kennt die Instanz ja nicht das individuelle Kommunikationsinterface und daher gehe ich davon aus, das das jeweilige Script selbst die Dinge beachten, die erforderlich sind

**Comment by DerGolo** [comment]
Hallo demel,

sorry, das vergaß ich zu erwähnen, es geht um Webfront. An der Stelle bringst du mich natürlich auf den Trichter, dass der selbe feature request bzw. der zum automatischen Kürzen von Nachrichten eher ein request in Richtung IP Symcon ist und nicht zu deinem Modul.

Danke :-)

Ich nutze ein Script zum Generieren der Nachrichten, dort habe ich die Limitierung nun selbst eingebaut.

```
$r = [];
if ($_IPS['recovery']) { $r['severity'] = 1; $r['subject'] = "Unserer Höhle gehts wieder besser."; }
else { $r['severity'] = 3; $r['subject'] = "Warnung"; $r['message'] = substr(GetValue(29888),0,170); }
echo json_encode($r);
```

**Comment by demel42** [comment]
Ich habe nochmal gerade im Sourcecode geschaut und siehe da, ich prüfe nur die Länge des Subject (auf max. 32).
Den Body kann (und sollte) ich natürlich auch prüfen. Sind die 170-Zeichen-Länge irgendwo aus der IPS-Doku oder durch austesten gewonnen?
Oder meinst du, das das ein Problem ist, weil, IPS das weiterleitet an ApplePush und ApplePush dann das Problem hat?
Wenn das Problem bei ApplePush liegt und bei Android die Grenzen anders sein sollen (?), müsste ich ja nach Endgerät unters unterschiedlich handhaben. 
Ich habe kein Problem da was einzubauen und etwas stabiler zu machen ist ja ein Zweck an sich.

**Comment by DerGolo** [comment]
Die Längenbeschränkungen liegen vermutlich hier:
https://clevertap.com/blog/what-are-push-notification-character-limits/#:~:text=What%20Are%20App%20Push%20Notification,titles%20and%20240%20for%20descriptions.

Ich habe es nicht explizit robust getestet, sondern nur festgestellt, dass sehr lange Nachrichten nicht am Handy ankommen. Nach einer Kürzung ging es dann. Daher kann ich auch nicht gang genau sagen, ob die Länge nur den body oder auch das subject betrifft, ich vermute beide in Summe.

Was ich meinte ist, dass wenn es bei den Anbietern wie Apple Beschränkungen gibt, dann betrifft das ja alle Nachrichten, nicht nur die aus deinem Modul, daher wäre es vermutlich sinnvoll, den FRQ bei IP Symcon zu stellen.

**Comment by demel42** [comment]
Hast grundsätzlich recht, das sollte die natürlich auch wissen und nach Möglichkeit umsetzen.
Wenn es da eine Reaktion gibt, wäre ich sehr daran interessiert
